name: CD

on:
  push:
    branches:
    - "!*"
    tags:
    - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - run: npm ci --legacy-peer-deps
    - run: npm run compile
    - run: npm test
      env:
        CI: true
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
